import type { ToolMetadataInput } from './metadata'
import { TOOL_COUNT } from '@/lib/toolMeta'

// Centralized per-route metadata. Each `layout.tsx` imports its own entry and
// passes it to `buildToolMetadata()` — the JSON-LD blocks stay in each page's
// own layout.tsx (a separate, ongoing structured-data pass), only the <head>
// metadata (title/description/canonical/robots/OG/Twitter) is centralized
// here. Adding a new tool means adding one entry below — no metadata
// boilerplate to duplicate.
export const TOOL_METADATA: Record<string, ToolMetadataInput> = {
  'about': {
    path: '/about',
    title: 'About EditPDF AI – Our Story and Privacy Approach',
    description: `EditPDF AI is an independent PDF tool suite. Learn who we are, how your files are handled, and why we keep ${TOOL_COUNT}+ tools permanently free.`,
    ogDescription: 'Learn how EditPDF AI builds free, private browser-based PDF tools for everyone.',
    twitterTitle: 'About EditPDF AI',
    twitterDescription: 'Free, private browser-based PDF tools built for everyone.',
  },
  'guides': {
    path: '/guides',
    title: 'PDF Guides & How-To Articles | EditPDF AI',
    description: 'Practical PDF guides: how to edit, compress, sign, merge, redact, and make PDFs searchable — with step-by-step instructions and free tool links.',
    ogDescription: 'Practical guides: edit, compress, sign, merge, redact and more — free tools included.',
    twitterDescription: 'Practical PDF guides with clear steps and direct links to free tools.',
  },
  'pdf-merger': {
    path: '/pdf-merger',
    title: 'Merge PDF Files Online Free — Combine PDFs in One Click',
    description: 'Merge multiple PDF files into one document online for free. Drag, reorder and combine any number of PDFs. Fast, secure and no signup required.',
    ogDescription: 'Drag and drop PDFs to merge them into a single document. Free, no signup, works in your browser.',
    twitterTitle: 'Merge PDF Files Online Free',
    twitterDescription: 'Combine multiple PDFs into one document instantly. No signup required.',
    ogImage: '/social/pdf-merger.png',
    ogImageAlt: 'Merge PDF Files Online Free',
  },
  'pdf-splitter': {
    path: '/pdf-splitter',
    title: 'Split PDF Online Free — Separate PDF Files by Range',
    description: 'Split a PDF into multiple files online for free. Separate every page or divide one PDF into custom page ranges directly in your browser.',
    ogTitle: 'Split PDF Online Free — Separate Files by Range',
    ogDescription: 'Split a PDF into separate files by custom page range or divide every page. Free, no signup needed.',
    twitterTitle: 'Split PDF Online Free',
    twitterDescription: 'Split any PDF into multiple files by page range. Free, instant and no signup.',
    ogImage: '/social/pdf-splitter.png',
    ogImageAlt: 'Split PDF Online Free',
  },
  'pdf-watermark': {
    path: '/pdf-watermark',
    title: 'Add a Watermark to PDF Online Free',
    description: 'Add text or image watermarks to PDFs online. Control the position, opacity, angle, font size and color. Free, with no signup or installation.',
    ogTitle: 'PDF Watermarker — Add Text & Image Watermarks to PDFs Free',
    ogDescription: 'Add custom text or image watermarks to any PDF. Control opacity, angle, position and color. Free, no signup.',
    twitterDescription: 'Add custom text or image watermarks to any PDF. Free, no signup required.',
    ogImage: '/social/pdf-watermark.png',
    ogImageAlt: 'PDF Watermarker — Add Watermarks Online Free',
  },
  'add-page-numbers': {
    path: '/add-page-numbers',
    title: 'Add Page Numbers to PDF Online Free — Number PDF Pages',
    description: 'Add page numbers to PDFs online for free. Choose the position, font, size, starting number and page range. No installation or signup required.',
    ogTitle: 'Add Page Numbers to PDF Online Free',
    ogDescription: 'Add customisable page numbers to any PDF online. Choose position, font and range. Free, no signup.',
    twitterDescription: 'Add page numbers to any PDF instantly. Customise position, font and range. Free online.',
    ogImage: '/social/add-page-numbers.png',
    ogImageAlt: 'Add Page Numbers to PDF Online Free',
  },
  'ai-pdf-form-filler': {
    path: '/ai-pdf-form-filler',
    title: 'AI PDF Form Filler — Autofill PDF Forms Online',
    description: 'Autofill W-9s, applications and scanned PDF forms with AI. Review, sign and download online. A free account includes five daily AI uses.',
    ogTitle: 'AI PDF Form Filler — Autofill Forms Online',
    ogDescription: 'Use AI to autofill PDF forms online, review every field, add a signature and download. A free account includes five AI uses daily.',
    twitterDescription: 'Autofill PDF forms with AI, review every field, sign and download. A free account includes five AI uses daily.',
    ogImage: '/social/ai-pdf-form-filler.png',
    ogImageAlt: 'AI PDF Form Filler — Autofill Any PDF Form Free',
  },
  'chat-with-pdf': {
    path: '/chat-with-pdf',
    title: 'Chat with PDF Online - AI Answers with Page Citations',
    description: 'Ask questions about any PDF and get grounded AI answers with verified quotes and page citations. Local text extraction, five free AI questions daily.',
    ogTitle: 'Chat with PDF - Cited Answers from Your Document',
    ogDescription: 'Ask questions in plain English and check every important answer against verified PDF page quotes.',
  },
  'contact': {
    path: '/contact',
    title: 'Contact Us | EditPDF AI',
    description: 'Get in touch with the EditPDF AI team. We\'re here to help with questions about our PDF tools, billing, or feedback.',
    ogDescription: 'Get in touch with the EditPDF AI team for help with PDF tools, billing, or feedback.',
    ogImage: '/opengraph-image',
    ogImageAlt: 'Contact EditPDF AI',
  },
  'delete-pages': {
    path: '/delete-pages',
    title: 'Delete PDF Pages Online Free — Remove Pages from PDF',
    description: 'Delete pages from a PDF online for free. Remove individual pages or a page range, then download the cleaned PDF instantly. No signup required.',
    ogDescription: 'Remove unwanted pages from any PDF instantly. Free, no signup, works in your browser.',
    twitterTitle: 'Delete PDF Pages Online Free',
    twitterDescription: 'Remove unwanted pages from any PDF instantly. Free, no signup.',
    ogImage: '/social/delete-pages.png',
    ogImageAlt: 'Delete PDF Pages Online Free',
  },
  'excel-to-pdf': {
    path: '/excel-to-pdf',
    title: 'Excel to PDF Converter Online Free — XLSX to PDF',
    description: 'Convert Excel spreadsheets to PDF online for free. Upload XLSX or XLS files and download a perfectly formatted PDF. Preserves tables and data. No signup.',
    ogDescription: 'Convert Excel XLSX and XLS files to PDF instantly. Preserves tables and formatting. Free, no signup.',
    twitterTitle: 'Excel to PDF Converter Online Free',
    twitterDescription: 'Convert Excel spreadsheets to PDF instantly. Free, no signup needed.',
    ogImage: '/social/excel-to-pdf.png',
    ogImageAlt: 'Excel to PDF Converter Online Free',
  },
  'export-pdf-comments': {
    path: '/export-pdf-comments',
    title: 'Export PDF Comments Online - Download Annotations as CSV or JSON',
    description: 'Extract PDF comments, highlights, notes, stamps, drawings, authors, dates, and replies into CSV or JSON locally in your browser.',
    ogTitle: 'Export PDF Comments Online - Private Annotation Audit',
    ogDescription: 'Inspect PDF review annotations and download structured CSV or JSON without uploading the document.',
    twitterTitle: 'Export PDF Comments Online',
    twitterDescription: 'Audit PDF comments, markup, authors, dates, and replies locally.',
  },
  'export-pdf-form-data': {
    path: '/export-pdf-form-data',
    title: 'Export PDF Form Data Online - Download CSV or JSON',
    description: 'Read fillable PDF fields and export their values, types, flags, options, and page locations as CSV or JSON with private browser processing.',
    ogTitle: 'Export PDF Form Data Online - Private CSV and JSON Export',
    ogDescription: 'Inspect AcroForm fields and download structured form data without uploading the PDF.',
    twitterTitle: 'Export PDF Form Data Online',
    twitterDescription: 'Download fillable PDF field data as safe CSV or structured JSON with local browser processing.',
  },
  'extract-pages': {
    path: '/extract-pages',
    title: 'Extract PDF Pages Online Free — Save Specific Pages as PDF',
    description: 'Extract specific pages from a PDF online for free. Save selected pages as a new PDF document. Works instantly in your browser — no install, no signup.',
    ogDescription: 'Extract and save specific pages from any PDF as a new document. Free, instant, no signup.',
    twitterTitle: 'Extract PDF Pages Online Free',
    twitterDescription: 'Save specific pages from any PDF as a new document. Free, instant, no signup.',
    ogImage: '/social/extract-pages.png',
    ogImageAlt: 'Extract PDF Pages Online Free',
  },
  'extract-pdf-attachments': {
    path: '/extract-pdf-attachments',
    title: 'Extract PDF Attachments Online - Download Embedded Files',
    description: 'Find and download files embedded inside a PDF. Extract document attachments, associated files, and file annotations privately in your browser.',
    ogTitle: 'Extract PDF Attachments Online - Private Embedded File Extractor',
    ogDescription: 'Recover files embedded inside a PDF and download them individually or as a ZIP without uploading the document.',
    twitterTitle: 'Extract PDF Attachments Online',
    twitterDescription: 'Download embedded PDF files individually or as a ZIP with private browser processing.',
  },
  'extract-pdf-bookmarks': {
    path: '/extract-pdf-bookmarks',
    title: 'Extract PDF Bookmarks Online - Export Outline to CSV or JSON',
    description: 'Read a PDF bookmark hierarchy, resolve page destinations, and export the document outline as CSV or JSON with private browser processing.',
    ogTitle: 'Extract PDF Bookmarks Online - Private Outline Exporter',
    ogDescription: 'Inspect nested PDF bookmarks and download their hierarchy and destinations without uploading the document.',
    twitterTitle: 'Extract PDF Bookmarks Online',
    twitterDescription: 'Export PDF bookmark trees and resolved page destinations as CSV or JSON locally in your browser.',
  },
  'extract-pdf-images': {
    path: '/extract-pdf-images',
    title: 'Extract Images from PDF Online - Download Embedded Pictures',
    description: 'Extract unique bitmap images from PDF pages as lossless PNG files. Preserve transparency and download images individually or as a ZIP.',
    ogTitle: 'Extract Images from PDF Online - Private Bitmap Extractor',
    ogDescription: 'Recover embedded bitmap images without rendering complete PDF pages. Free local browser processing.',
    twitterTitle: 'Extract Images from PDF Online',
    twitterDescription: 'Download unique embedded PDF images as lossless PNG files without uploading the document.',
  },
  'extract-pdf-links': {
    path: '/extract-pdf-links',
    title: 'Extract PDF Links Online - Export URLs and Page Destinations',
    description: 'Find web, email, internal-page, external-PDF, and other clickable links in a PDF, then export a safe CSV or JSON audit locally.',
    ogTitle: 'Extract PDF Links Online - Private Link Annotation Audit',
    ogDescription: 'Inspect clickable PDF annotations and export their targets without uploading the document or opening any link.',
    twitterTitle: 'Extract PDF Links Online',
    twitterDescription: 'Audit PDF link annotations and download CSV or JSON locally in your browser.',
  },
  'html-to-pdf': {
    path: '/html-to-pdf',
    title: 'HTML to PDF Converter Online Free — Webpage to PDF',
    description: 'Convert HTML files or web pages to PDF online for free. Paste HTML code or a URL and download a perfectly rendered PDF. Supports CSS styling. No signup.',
    ogDescription: 'Convert HTML code or web pages to PDF instantly. Supports CSS styling. Free, no signup.',
    twitterTitle: 'HTML to PDF Converter Online Free',
    twitterDescription: 'Convert HTML or web pages to PDF instantly. Supports CSS. Free, no signup.',
    ogImage: '/social/html-to-pdf.png',
    ogImageAlt: 'HTML to PDF Converter Online Free',
  },
  'image-to-pdf': {
    path: '/image-to-pdf',
    title: 'Image to PDF Converter Online Free — JPG, PNG to PDF',
    description: 'Convert JPG, PNG and WebP images to PDF online for free. Combine multiple images and adjust page size, orientation and margins. No signup required.',
    ogDescription: 'Convert JPG, PNG and other images to PDF online for free. Combine multiple images into one PDF.',
    twitterTitle: 'Image to PDF Converter Online Free',
    twitterDescription: 'Convert JPG, PNG and other images to PDF instantly. Free, no signup needed.',
    ogImage: '/social/image-to-pdf.png',
    ogImageAlt: 'Image to PDF Converter Online Free',
  },
  'mind-map': {
    path: '/mind-map',
    title: 'AI Mind Map Generator from PDF — Visualise Any Document',
    description: 'Generate an interactive mind map from any PDF with AI. Visualise reports, research papers, books and notes as a structured knowledge graph.',
    ogDescription: 'Turn any PDF into an interactive visual mind map with AI. Free online, no signup needed.',
    twitterTitle: 'AI Mind Map Generator from PDF',
    twitterDescription: 'Turn any PDF into a visual mind map with AI. Free online, no signup.',
    ogImage: '/social/mind-map.png',
    ogImageAlt: 'AI Mind Map Generator from PDF',
  },
  'odt-to-pdf': {
    path: '/odt-to-pdf',
    title: 'ODT to PDF Converter Online Free — OpenDocument to PDF',
    description: 'Convert ODT (OpenDocument Text) files to PDF online for free. Works with LibreOffice and OpenOffice documents. Fast, accurate and no signup required.',
    ogDescription: 'Convert ODT OpenDocument files to PDF instantly. Works with LibreOffice and OpenOffice. Free, no signup.',
    twitterTitle: 'ODT to PDF Converter Online Free',
    twitterDescription: 'Convert ODT files to PDF instantly. Works with LibreOffice. Free, no signup.',
    ogImage: '/social/odt-to-pdf.png',
    ogImageAlt: 'ODT to PDF Converter Online Free',
  },
  'pdf-annotate': {
    path: '/pdf-annotate',
    title: 'Annotate PDF Online — Highlight, Comment & Draw',
    description: 'Annotate PDFs online for free. Highlight text, add comments, draw shapes, insert sticky notes and add freehand markup directly in your browser.',
    ogTitle: 'Annotate PDF Online Free — Highlight, Comment & Mark Up PDFs',
    ogDescription: 'Highlight, comment and draw on any PDF online for free. No signup, works in your browser.',
    twitterTitle: 'Annotate PDF Online Free',
    twitterDescription: 'Highlight, comment and mark up any PDF instantly. Free, no signup needed.',
    ogImage: '/social/pdf-annotate.png',
    ogImageAlt: 'Annotate PDF Online Free',
  },
  'pdf-bookmarks-manager': {
    path: '/pdf-bookmarks-manager',
    title: 'PDF Bookmarks Manager Online - Add, Edit and Remove Bookmarks',
    description: 'Add, rename, nest, reorder, retarget, open, close, or delete PDF bookmarks and download a new PDF with private browser processing.',
    ogTitle: 'PDF Bookmarks Manager Online - Private Outline Editor',
    ogDescription: 'Edit a PDF outline tree and download a new navigable PDF without uploading the document.',
    twitterTitle: 'PDF Bookmarks Manager Online',
    twitterDescription: 'Add, rename, nest, reorder, retarget, and delete PDF bookmarks locally in your browser.',
  },
  'pdf-compare': {
    path: '/pdf-compare',
    title: 'Compare PDF Files Online - Find Visual and Text Changes',
    description: 'Compare two PDFs page by page to find visible, textual, page-size, and page-count changes. Free private browser processing with clear difference maps.',
    ogTitle: 'Compare PDF Files Online - Find Every Page Change',
    ogDescription: 'Review visual and textual differences between two PDFs without uploading either document.',
    twitterTitle: 'Compare PDF Files Online',
    twitterDescription: 'Find visual and text changes page by page with private browser processing.',
  },
  'pdf-compressor': {
    path: '/pdf-compressor',
    title: 'Compress PDF Online Free — Reduce PDF File Size',
    description: 'Compress PDF files online for free. Reduce PDF size without losing quality. Shrink large PDFs for email, upload, or sharing in seconds.',
    ogDescription: 'Reduce PDF file size without losing quality. Free, instant, no signup required.',
    twitterTitle: 'Compress PDF Online Free',
    twitterDescription: 'Shrink any PDF file instantly without losing quality.',
    ogImage: '/social/pdf-compressor.png',
    ogImageAlt: 'Compress PDF Online Free',
  },
  'pdf-cropper': {
    path: '/pdf-cropper',
    title: 'Crop PDF Pages Online Free — Trim PDF Margins',
    description: 'Crop PDF pages online for free. Trim margins, remove whitespace or select a specific area on one page or the entire document. No installation needed.',
    ogDescription: 'Trim margins and crop any PDF page online. Free, no signup, works instantly in your browser.',
    twitterTitle: 'Crop PDF Pages Online Free',
    twitterDescription: 'Trim margins and crop any PDF page instantly. Free, no signup needed.',
    ogImage: '/social/pdf-cropper.png',
    ogImageAlt: 'Crop PDF Pages Online Free',
  },
  'pdf-editor': {
    path: '/pdf-editor',
    title: 'Edit a PDF Without Adobe Acrobat — Free Online PDF Editor',
    description: 'Edit a PDF without installing Adobe Acrobat — add text, images, highlights, signatures and stamps in your browser. No signup, nothing uploaded.',
    ogDescription: 'Add text, images, shapes, signatures and stamps to any PDF — no Adobe install, no signup. Reorder and rotate pages, then download.',
    twitterTitle: 'Edit a PDF Without Adobe Acrobat',
    twitterDescription: 'Add text, images, shapes, signatures and stamps to any PDF. Free, no signup, no Adobe install required.',
    ogImage: '/social/pdf-editor.png',
    ogImageAlt: 'Edit a PDF Without Adobe Acrobat — Free Online PDF Editor',
  },
  'pdf-flatten': {
    path: '/pdf-flatten',
    title: 'Flatten PDF Online - Make Forms and Annotations Permanent',
    description: 'Flatten PDF form fields or bake every visible page element into a consistent copy. Free private browser processing with no file upload or account.',
    ogDescription: 'Choose a quality-preserving form flatten or a complete visual flatten. Free and private in your browser.',
    twitterDescription: 'Flatten PDF forms and visible annotations privately in your browser.',
    ogImage: '/opengraph-image',
    ogImageAlt: 'EditPDF AI Flatten PDF',
  },
  'pdf-form-builder': {
    path: '/pdf-form-builder',
    title: 'PDF Form Builder Online Free — Create Fillable PDF Forms',
    description: 'Create fillable PDF forms online for free. Add text fields, checkboxes, dropdowns and signatures without installing specialist design software.',
    ogDescription: 'Create professional fillable PDF forms with text fields, checkboxes, signatures and more. Free online.',
    twitterTitle: 'PDF Form Builder Online Free',
    twitterDescription: 'Create professional fillable PDF forms with drag-and-drop. Free, no signup needed.',
    ogImage: '/social/pdf-form-builder.png',
    ogImageAlt: 'PDF Form Builder Online Free',
  },
  'pdf-ocr': {
    path: '/pdf-ocr',
    title: 'PDF OCR Online Free — Extract Text from Scanned PDF',
    description: 'Convert scanned PDFs and images to searchable, editable text with AI OCR. Supports 100+ languages. Fast, accurate and free online — no install required.',
    ogDescription: 'Convert scanned PDFs to searchable text with AI OCR. Supports 100+ languages. Free, no install.',
    twitterTitle: 'PDF OCR Online Free',
    twitterDescription: 'Convert scanned PDFs to searchable editable text with AI OCR. Free, no install.',
    ogImage: '/social/pdf-ocr.png',
    ogImageAlt: 'PDF OCR — Extract Text from Scanned PDF',
  },
  'pdf-page-labels': {
    path: '/pdf-page-labels',
    title: 'PDF Page Labels Online - Roman Numerals, Prefixes and Sections',
    description: 'Add or edit PDF page labels with decimal numbers, Roman numerals, letters, prefixes, and section restarts using private browser processing.',
    ogTitle: 'PDF Page Labels Online - Private Label Range Editor',
    ogDescription: 'Create viewer navigation labels for PDF front matter, chapters, appendices, and numbered sections without changing page artwork.',
    twitterTitle: 'PDF Page Labels Online',
    twitterDescription: 'Set PDF page labels, prefixes, styles, and numbering restarts locally in your browser.',
  },
  'pdf-page-manager': {
    path: '/pdf-page-manager',
    title: 'PDF Page Manager — Reorder, Delete & Add Pages',
    description: 'Manage PDF pages online for free. Drag to reorder, delete unwanted pages, add blank pages and rotate individual pages. No software install required.',
    ogTitle: 'PDF Page Manager — Reorder, Delete & Add PDF Pages Online',
    ogDescription: 'Drag to reorder, delete or add pages to any PDF. Free, works instantly in your browser.',
    twitterTitle: 'PDF Page Manager Online',
    twitterDescription: 'Reorder, delete or add pages to any PDF instantly. Free, no signup needed.',
    ogImage: '/social/pdf-page-manager.png',
    ogImageAlt: 'PDF Page Manager Online',
  },
  'pdf-password-lock': {
    path: '/pdf-password-lock',
    title: 'PDF Password Lock — Password Protect PDF Free Online',
    description: 'Add a password to any PDF instantly. Encrypt your PDF with AES-256 security in your browser — free, no upload, no account required.',
    ogDescription: 'Add a password to any PDF instantly. AES-256 encryption, free, no account, no upload.',
    twitterDescription: 'Add a password to any PDF instantly. AES-256 encryption, free, no account.',
    ogImage: '/social/pdf-password-lock.png',
    ogImageAlt: 'PDF Password Lock',
  },
  'pdf-redactor': {
    path: '/pdf-redactor',
    title: 'Redact PDF Online Free — Permanently Remove Sensitive Text',
    description: 'Redact sensitive information from PDF files online for free. Permanently black out names, addresses, SSNs and confidential data. Secure, no server upload.',
    ogDescription: 'Permanently black out sensitive text and data from any PDF. Free, secure, no server upload.',
    twitterTitle: 'Redact PDF Online Free',
    twitterDescription: 'Permanently remove sensitive information from any PDF. Secure, no server upload.',
    ogImage: '/social/pdf-redactor.png',
    ogImageAlt: 'Redact PDF Online Free',
  },
  'pdf-repair': {
    path: '/pdf-repair',
    title: 'Repair PDF Online - Recover a Damaged PDF',
    description: 'Repair recoverable PDF structure errors privately in your browser. Free local processing with no file upload, no account, and no change to the original file.',
    ogDescription: 'Rebuild recoverable PDF structure errors privately in your browser. Free, no upload, no account.',
    twitterDescription: 'Repair recoverable PDF structure errors privately in your browser.',
    ogImage: '/opengraph-image',
    ogImageAlt: 'EditPDF AI Repair PDF',
  },
  'pdf-signer': {
    path: '/pdf-signer',
    title: 'Sign PDF Online Free — eSign Documents Instantly',
    description: 'Sign PDFs online for free. Draw, type or upload your signature, place it anywhere in the document and download it instantly. No account required.',
    ogDescription: 'Draw, type or upload a signature and sign any PDF for free. No account needed.',
    twitterTitle: 'Sign PDF Online Free',
    twitterDescription: 'Draw, type or upload your signature and sign any PDF instantly. Free, no account needed.',
    ogImage: '/social/pdf-signer.png',
    ogImageAlt: 'Sign PDF Online Free',
  },
  'pdf-summarizer': {
    path: '/pdf-summarizer',
    title: 'AI PDF Summarizer Online Free — Summarize Any PDF Instantly',
    description: 'Summarize any PDF document with AI in seconds. Get concise key points, chapter summaries and action items from long reports, research papers and contracts.',
    ogDescription: 'Get AI-powered summaries of any PDF in seconds. Key points, chapter breakdowns and action items.',
    twitterTitle: 'AI PDF Summarizer Online Free',
    twitterDescription: 'Summarize any PDF with AI in seconds. Key points, summaries and action items.',
    ogImage: '/social/pdf-summarizer.png',
    ogImageAlt: 'AI PDF Summarizer Online Free',
  },
  'pdf-to-excel': {
    path: '/pdf-to-excel',
    title: 'PDF to Excel Converter Online Free — PDF to XLSX',
    description: 'Convert PDF tables into editable Excel XLSX spreadsheets online. Extract accurate rows and columns with AI-powered conversion. No signup required.',
    ogDescription: 'Convert PDF tables to editable Excel XLSX instantly. AI-powered accuracy. Free, no signup.',
    twitterTitle: 'PDF to Excel Converter Online Free',
    twitterDescription: 'Convert PDF tables to editable Excel spreadsheets instantly. AI-powered. Free, no signup.',
    ogImage: '/social/pdf-to-excel.png',
    ogImageAlt: 'PDF to Excel Converter Online Free',
  },
  'pdf-to-images': {
    path: '/pdf-to-images',
    title: 'PDF to Image Converter Online Free — PDF to JPG, PNG',
    description: 'Convert PDF pages to high-quality JPG or PNG images online for free. Extract every page as an image or choose specific pages. No signup, works in browser.',
    ogDescription: 'Convert PDF pages to high-quality JPG or PNG images. Free, instant, no signup needed.',
    twitterTitle: 'PDF to Image Converter Online Free',
    twitterDescription: 'Convert PDF pages to JPG or PNG images instantly. Free, no signup.',
    ogImage: '/social/pdf-to-images.png',
    ogImageAlt: 'PDF to Image Converter Online Free',
  },
  'pdf-to-ppt': {
    path: '/pdf-to-ppt',
    title: 'PDF to PowerPoint Converter Online Free — PDF to PPTX',
    description: 'Convert PDFs into editable PowerPoint presentations online. Turn each PDF page into a PPTX slide while preserving text, images and layout.',
    ogDescription: 'Convert PDF to editable PowerPoint PPTX slides. Preserves text and images. Free, no signup.',
    twitterTitle: 'PDF to PowerPoint Converter Online Free',
    twitterDescription: 'Convert PDF to editable PowerPoint slides instantly. Free, no signup.',
    ogImage: '/social/pdf-to-ppt.png',
    ogImageAlt: 'PDF to PowerPoint Converter Online Free',
  },
  'pdf-to-word': {
    path: '/pdf-to-word',
    title: 'PDF to Word Converter Online Free — PDF to DOCX',
    description: 'Convert PDFs into editable Word DOCX documents online. Preserve text, tables and layout with fast AI-powered conversion. No signup required.',
    ogDescription: 'Convert any PDF to an editable Word DOCX file. Preserves text, tables and layout. Free, no signup.',
    twitterTitle: 'PDF to Word Converter Online Free',
    twitterDescription: 'Convert PDF to editable Word DOCX instantly. Preserves layout. Free, no signup.',
    ogImage: '/social/pdf-to-word.png',
    ogImageAlt: 'PDF to Word Converter Online Free',
  },
  'pdf-translator': {
    path: '/pdf-translator',
    title: 'AI PDF Translator — Translate PDFs Online',
    description: 'Translate PDF documents into 77 languages with AI. Translate contracts, reports and forms in seconds, then download the result online.',
    ogTitle: 'AI PDF Translator Online Free — Translate PDF to Any Language',
    ogDescription: 'Translate any PDF into 77 languages with AI. Translate documents online and download the result.',
    twitterTitle: 'AI PDF Translator Online Free',
    twitterDescription: 'Translate any PDF into 77 languages with AI and download the result online.',
    ogImage: '/social/pdf-translator.png',
    ogImageAlt: 'AI PDF Translator Online Free',
  },
  'pdf-unlock': {
    path: '/pdf-unlock',
    title: 'Unlock PDF Online - Remove a Known PDF Password',
    description: 'Remove password protection from a PDF you own. Free, private browser processing with no file upload, no account, and no loss of quality.',
    ogDescription: 'Remove a known PDF password privately in your browser. Free, no upload, no account.',
    twitterDescription: 'Remove a known PDF password privately in your browser.',
    ogImage: '/opengraph-image',
    ogImageAlt: 'EditPDF AI Unlock PDF',
  },
  'pdf-viewer': {
    path: '/pdf-viewer',
    title: 'PDF Viewer Online Free — Open & Read PDF in Browser',
    description: 'View PDF files online for free. Open, zoom, search and navigate any PDF in your browser. Fast, secure and works without any software installation.',
    ogDescription: 'Open and read any PDF in your browser. Zoom, search and navigate instantly. Free, no install.',
    twitterTitle: 'PDF Viewer Online Free',
    twitterDescription: 'Open, zoom and read any PDF in your browser. Free, no install needed.',
    ogImage: '/social/pdf-viewer.png',
    ogImageAlt: 'PDF Viewer Online Free',
  },
  'ppt-to-pdf': {
    path: '/ppt-to-pdf',
    title: 'PowerPoint to PDF Converter Online Free — PPTX to PDF',
    description: 'Convert PowerPoint presentations to PDF online for free. Upload PPTX or PPT and get a perfect PDF with all slides. Preserves fonts, images and animations.',
    ogDescription: 'Convert PowerPoint PPTX and PPT files to PDF instantly. Preserves all slides. Free, no signup.',
    twitterTitle: 'PowerPoint to PDF Converter Online Free',
    twitterDescription: 'Convert PowerPoint slides to PDF instantly. Free, no signup needed.',
    ogImage: '/social/ppt-to-pdf.png',
    ogImageAlt: 'PowerPoint to PDF Converter Online Free',
  },
  'pricing': {
    path: '/pricing',
    title: 'Pricing & Plans | EditPDF AI',
    description: 'Compare EditPDF AI Free and Pro plans. Get unlimited AI form filling, OCR, translation, mind maps and quiz creation. Cancel Pro anytime.',
    ogDescription: 'Compare free and Pro plans. Unlimited AI tools, OCR, translation and more with Pro. Cancel anytime.',
    twitterDescription: 'Compare free and Pro plans. Unlimited AI tools with Pro. Cancel anytime.',
    ogImage: '/opengraph-image',
    ogImageAlt: 'EditPDF AI Pricing',
  },
  'privacy': {
    path: '/privacy',
    title: 'Privacy Policy | EditPDF AI',
    description: 'Read the EditPDF AI privacy policy. Learn how we handle your data, what we collect, and your rights under GDPR and CCPA.',
    ogDescription: 'Read the EditPDF AI privacy policy. Learn how we handle your data and your rights under GDPR and CCPA.',
    ogImage: '/opengraph-image',
    ogImageAlt: 'EditPDF AI Privacy Policy',
  },
  'quiz-creator': {
    path: '/quiz-creator',
    title: 'AI Quiz Creator from PDF — Generate Quizzes Instantly',
    description: 'Create quizzes and flashcards from PDFs with AI. Generate multiple-choice, true-or-false and open-ended questions from your study materials.',
    ogDescription: 'Generate quizzes and flashcards from any PDF with AI. Perfect for studying and revision. Free online.',
    twitterTitle: 'AI Quiz Creator from PDF',
    twitterDescription: 'Generate quizzes and flashcards from any PDF with AI. Free online, no signup.',
    ogImage: '/social/quiz-creator.png',
    ogImageAlt: 'AI Quiz Creator from PDF',
  },
  'remove-pdf-links': {
    path: '/remove-pdf-links',
    title: 'Remove Links from PDF Online - Disable All Clickable Links',
    description: 'Remove web, email, page, file, form, and JavaScript link annotations from a PDF locally while preserving visible page content.',
    ogTitle: 'Remove PDF Links Online - Private Browser Tool',
    ogDescription: 'Create a link-free PDF copy without uploading the document or changing visible link text.',
    twitterTitle: 'Remove PDF Links Online',
    twitterDescription: 'Disable clickable PDF link annotations privately in your browser.',
  },
  'remove-pdf-metadata': {
    path: '/remove-pdf-metadata',
    title: 'Remove PDF Metadata Online - Clean Hidden Document Properties',
    description: 'Remove PDF properties, XMP packets, document IDs, page metadata, and optional annotation identity data privately in your browser.',
    ogTitle: 'Remove PDF Metadata Online - Private Document Cleaner',
    ogDescription: 'Clean hidden PDF properties and identifiers locally without changing page quality.',
    twitterTitle: 'Remove PDF Metadata Online',
    twitterDescription: 'Strip hidden document properties, XMP metadata, and identifiers with private browser processing.',
  },
  'rotate-pdf': {
    path: '/rotate-pdf',
    title: 'Rotate PDF Online Free — Rotate Pages in Seconds',
    description: 'Rotate PDF pages online for free. Rotate a single page, all pages, or a custom range — 90°, 180° or 270°. Works in your browser, no install needed.',
    ogDescription: 'Rotate any PDF page 90°, 180° or 270°. Works instantly in your browser — no install, no signup.',
    twitterTitle: 'Rotate PDF Online Free',
    twitterDescription: 'Rotate any PDF page 90°, 180° or 270° instantly in your browser.',
    ogImage: '/social/rotate-pdf.png',
    ogImageAlt: 'Rotate PDF Online Free',
  },
  'rtf-to-pdf': {
    path: '/rtf-to-pdf',
    title: 'RTF to PDF Converter Online Free — Rich Text to PDF',
    description: 'Convert RTF (Rich Text Format) files to PDF online for free. Preserves bold, italic, fonts and formatting. Fast, secure and no signup required.',
    ogDescription: 'Convert RTF files to PDF instantly. Preserves fonts and formatting. Free, no signup.',
    twitterTitle: 'RTF to PDF Converter Online Free',
    twitterDescription: 'Convert RTF to PDF instantly. Preserves formatting. Free, no signup.',
    ogImage: '/social/rtf-to-pdf.png',
    ogImageAlt: 'RTF to PDF Converter Online Free',
  },
  'scan-to-pdf': {
    path: '/scan-to-pdf',
    title: 'Scan to PDF Online Free — Camera Document Scanner',
    description: 'Turn your camera into a document scanner. Auto-detect edges, fix perspective, and export a clean multi-page PDF. Free, no signup, runs in your browser.',
    ogDescription: 'Capture paper documents with your camera, auto-crop and straighten them, and save a multi-page PDF. Free and private — nothing leaves your browser.',
    twitterDescription: 'Capture paper documents with your camera and export a clean multi-page PDF. Free, no signup needed.',
    ogImage: '/opengraph-image',
    ogImageAlt: 'Scan to PDF — Camera Document Scanner',
  },
  'support': {
    path: '/support',
    title: 'Help & Support | EditPDF AI',
    description: 'Find answers to common questions about EditPDF AI tools, billing, and account management. Contact support if you need further help.',
    ogDescription: 'Find answers to common questions about EditPDF AI tools, billing, and account management.',
    ogImage: '/opengraph-image',
    ogImageAlt: 'EditPDF AI Support',
  },
  'terms': {
    path: '/terms',
    title: 'Terms of Service | EditPDF AI',
    description: 'Read the EditPDF AI terms of service. Understand the conditions of use for our PDF editing, conversion, and AI tools.',
    ogDescription: 'Read the EditPDF AI terms of service and conditions of use for our PDF and AI tools.',
    ogImage: '/opengraph-image',
    ogImageAlt: 'EditPDF AI Terms of Service',
  },
  'txt-to-pdf': {
    path: '/txt-to-pdf',
    title: 'TXT to PDF Converter Online Free — Text File to PDF',
    description: 'Convert plain text TXT files to PDF online for free. Choose font, size and margins. Download a clean, formatted PDF in seconds. No signup required.',
    ogDescription: 'Convert plain text TXT files to clean PDFs. Choose font and formatting. Free, no signup.',
    twitterTitle: 'TXT to PDF Converter Online Free',
    twitterDescription: 'Convert plain text files to PDF instantly. Free, no signup needed.',
    ogImage: '/social/txt-to-pdf.png',
    ogImageAlt: 'TXT to PDF Converter Online Free',
  },
  'word-to-pdf': {
    path: '/word-to-pdf',
    title: 'Word to PDF Converter Online Free — DOCX to PDF',
    description: 'Convert Word documents to PDF online for free. Upload DOCX or DOC files and get a perfect PDF instantly. Preserves fonts, formatting and images. No signup.',
    ogDescription: 'Convert Word DOCX and DOC files to PDF instantly. Preserves formatting. Free, no signup.',
    twitterTitle: 'Word to PDF Converter Online Free',
    twitterDescription: 'Convert Word to PDF instantly. Preserves fonts and formatting. Free, no signup.',
    ogImage: '/social/word-to-pdf.png',
    ogImageAlt: 'Word to PDF Converter Online Free',
  },
}
