import type { PageSeoConfig } from './metadata'
import { buildPageMetadata } from './metadata'
import { TOOL_COUNT } from '@/lib/toolMeta'
import { FREE_AI_DAILY_LIMIT } from '@/lib/productMessaging'

// Root-layout fallback only. It deliberately has no canonical because a root
// canonical would be inherited by child routes that omit one. Every resolved
// page uses PAGE_SEO or the same builder for dynamic guide data.
export const SITE_DEFAULT_SEO: PageSeoConfig = {
  path: '/',
  canonicalPath: null,
  title: 'EditPDF AI — Online PDF Tools',
  description: 'Edit, organize, convert and understand PDF documents with browser-based and AI-assisted tools from EditPDF AI.',
  ogImageAlt: 'EditPDF AI online PDF tools',
}

// Single source of truth for every fixed page route. Route components pass an
// entry to buildPageMetadata(), which supplies canonical, robots, Open Graph
// and Twitter fields consistently. Dynamic guide routes use the same builder
// with their typed guide records.
export const PAGE_SEO = {
  'home': {
    path: '/',
    title: `EditPDF AI: Free Online PDF Editor & ${TOOL_COUNT} PDF Tools`,
    description: `Edit, sign, merge, compress and convert PDFs with ${TOOL_COUNT} online tools. Core tools run in your browser and need no account or software install.`,
    ogImage: '/social/home-constellation.png',
    ogImageAlt: `EditPDF AI — online PDF editor and ${TOOL_COUNT} PDF tools`,
  },
  'about': {
    path: '/about',
    title: 'About EditPDF AI — PDF Tools & Data Handling',
    description: 'Learn about EditPDF AI, its browser-based PDF tools, account-based AI features and the approach used for document processing and product support.',
    ogDescription: 'Learn about EditPDF AI, its browser-based PDF tools, account-based AI features and document processing approach.',
    twitterTitle: 'About EditPDF AI',
    twitterDescription: 'Learn about EditPDF AI, its PDF tools, AI features and document processing approach.',
  },
  'guides': {
    path: '/guides',
    title: 'PDF Guides & How-To Articles | EditPDF AI',
    description: 'Practical PDF guides for editing, compressing, signing, merging, handling sensitive content and making scanned documents searchable with OCR.',
    ogDescription: 'Practical guides for editing, compressing, signing, merging and understanding PDF documents.',
    twitterDescription: 'Practical PDF guides with clear steps and direct links to free tools.',
  },
  'pdf-merger': {
    path: '/pdf-merger',
    title: 'Merge PDF Files Online Free — Combine PDFs in One Click',
    description: 'Merge multiple PDF files into one document online for free. Drag to reorder files and combine them locally in your browser with no signup.',
    ogDescription: 'Drag and drop PDFs to merge them into a single document. Free, no signup, works in your browser.',
    twitterTitle: 'Merge PDF Files Online Free',
    twitterDescription: 'Combine multiple PDFs into one document instantly. No signup required.',
    ogImage: '/social/pdf-merger.png',
    ogImageAlt: 'Merge PDF Files Online Free',
  },
  'pdf-splitter': {
    path: '/pdf-splitter',
    title: 'Split PDF Online Free — Separate PDF Files by Range',
    description: 'Split a PDF into multiple files online for free. Separate every page or divide one PDF into custom page ranges directly in your browser.',
    ogTitle: 'Split PDF Online Free — Separate Files by Range',
    ogDescription: 'Split a PDF into separate files by custom page range or divide every page. Free, no signup needed.',
    twitterTitle: 'Split PDF Online Free',
    twitterDescription: 'Split a supported PDF into multiple files by page range. Free browser processing with no signup.',
    ogImage: '/social/pdf-splitter.png',
    ogImageAlt: 'Split PDF Online Free',
  },
  'pdf-watermark': {
    path: '/pdf-watermark',
    title: 'Add a Watermark to PDF Online Free',
    description: 'Add text or image watermarks to PDFs online. Control the position, opacity, angle, font size and color. Free, with no signup or installation.',
    ogTitle: 'PDF Watermarker — Add Text & Image Watermarks to PDFs Free',
    ogDescription: 'Add custom text or image watermarks to PDF pages. Control opacity, angle, position and color with local browser processing.',
    twitterDescription: 'Add custom text or image watermarks to PDF pages with no signup required.',
    ogImage: '/social/pdf-watermark.png',
    ogImageAlt: 'PDF Watermarker — Add Watermarks Online Free',
  },
  'add-page-numbers': {
    path: '/add-page-numbers',
    title: 'Add Page Numbers to PDF Online Free — Number PDF Pages',
    description: 'Add page numbers to PDFs online for free. Choose the position, font, size, starting number and page range. No installation or signup required.',
    ogTitle: 'Add Page Numbers to PDF Online Free',
    ogDescription: 'Add customisable page numbers to a PDF online. Choose the position, font and range with free browser processing and no signup.',
    twitterDescription: 'Add page numbers to a PDF. Customise the position, font and page range in your browser.',
    ogImage: '/social/add-page-numbers.png',
    ogImageAlt: 'Add Page Numbers to PDF Online Free',
  },
  'ai-pdf-form-filler': {
    path: '/ai-pdf-form-filler',
    title: 'AI PDF Form Filler — Autofill PDF Forms Online',
    description: `Use AI to suggest values for supported PDF forms, then review and download. Signed-in Free includes ${FREE_AI_DAILY_LIMIT} AI actions per UTC day. Review all AI output before use.`,
    ogTitle: 'AI PDF Form Filler — Autofill Forms Online',
    ogDescription: `Use AI to suggest PDF form values, review every field, add a visual signature, and download. Free includes ${FREE_AI_DAILY_LIMIT} AI actions per UTC day.`,
    twitterDescription: `Suggest PDF form values with AI, review the fields, and download. Free includes ${FREE_AI_DAILY_LIMIT} AI actions per UTC day.`,
    ogImage: '/social/ai-pdf-form-filler.png',
    ogImageAlt: 'AI PDF Form Filler — suggested values for detected form fields',
  },
  'chat-with-pdf': {
    path: '/chat-with-pdf',
    title: 'Chat with PDF Online - AI Answers with Page Citations',
    description: 'Ask questions about searchable PDF text and receive AI answers with page references and supporting quotes. Review each answer against the source document.',
    ogTitle: 'Chat with PDF - Cited Answers from Your Document',
    ogDescription: 'Ask questions in plain English and check every important answer against verified PDF page quotes.',
  },
  'contact': {
    path: '/contact',
    title: 'Contact Us | EditPDF AI',
    description: 'Email EditPDF AI support for help with PDF tools, account access, subscription billing, privacy and data requests, technical issues or product feedback.',
    ogDescription: 'Email EditPDF AI support for help with PDF tools, account access, billing, privacy requests, or feedback.',
    ogImage: '/opengraph-image',
    ogImageAlt: 'Contact EditPDF AI',
  },
  'delete-pages': {
    path: '/delete-pages',
    title: 'Delete PDF Pages Online Free — Remove Pages from PDF',
    description: 'Delete pages from a PDF online for free. Remove individual pages or a page range, then download the cleaned PDF instantly. No signup required.',
    ogDescription: 'Remove unwanted pages from a supported PDF locally in your browser. Free to use with no signup.',
    twitterTitle: 'Delete PDF Pages Online Free',
    twitterDescription: 'Remove unwanted pages from a supported PDF in your browser. Free, no signup.',
    ogImage: '/social/delete-pages.png',
    ogImageAlt: 'Delete PDF Pages Online Free',
  },
  'excel-to-pdf': {
    path: '/excel-to-pdf',
    title: 'Excel to PDF Converter Online Free — XLSX to PDF',
    description: 'Convert XLSX, XLS or CSV worksheets into PDF tables online. Select sheets, preview the generated pages and download the result with no account required.',
    ogDescription: 'Convert XLSX, XLS or CSV worksheet data into PDF tables online. Free, no signup required.',
    twitterTitle: 'Excel to PDF Converter Online Free',
    twitterDescription: 'Convert Excel spreadsheets to PDF instantly. Free, no signup needed.',
    ogImage: '/social/excel-to-pdf.png',
    ogImageAlt: 'Excel to PDF Converter Online Free',
  },
  'export-pdf-comments': {
    path: '/export-pdf-comments',
    title: 'Export PDF Comments Online - Download Annotations as CSV or JSON',
    description: 'Extract PDF comments, highlights, notes, stamps, drawings, authors, dates and replies into CSV or JSON with private processing in your browser.',
    ogTitle: 'Export PDF Comments Online - Private Annotation Audit',
    ogDescription: 'Inspect PDF review annotations and download structured CSV or JSON without uploading the document.',
    twitterTitle: 'Export PDF Comments Online',
    twitterDescription: 'Audit PDF comments, markup, authors, dates, and replies locally.',
  },
  'export-pdf-form-data': {
    path: '/export-pdf-form-data',
    title: 'Export PDF Form Data Online - Download CSV or JSON',
    description: 'Read fillable PDF fields and export their values, types, flags, options, and page locations as CSV or JSON with private browser processing.',
    ogTitle: 'Export PDF Form Data Online - Private CSV and JSON Export',
    ogDescription: 'Inspect AcroForm fields and download structured form data without uploading the PDF.',
    twitterTitle: 'Export PDF Form Data Online',
    twitterDescription: 'Download fillable PDF field data as safe CSV or structured JSON with local browser processing.',
  },
  'extract-pages': {
    path: '/extract-pages',
    title: 'Extract PDF Pages Online Free — Save Specific Pages as PDF',
    description: 'Extract specific pages from a PDF online for free. Save selected pages as a new PDF document. Works instantly in your browser — no install, no signup.',
    ogDescription: 'Extract and save selected pages from a supported PDF as a new document. Free browser processing with no signup.',
    twitterTitle: 'Extract PDF Pages Online Free',
    twitterDescription: 'Save selected PDF pages as a new document with free browser processing and no signup.',
    ogImage: '/social/extract-pages.png',
    ogImageAlt: 'Extract PDF Pages Online Free',
  },
  'extract-pdf-attachments': {
    path: '/extract-pdf-attachments',
    title: 'Extract PDF Attachments Online - Download Embedded Files',
    description: 'Find and download files embedded inside a PDF. Extract document attachments, associated files, and file annotations privately in your browser.',
    ogTitle: 'Extract PDF Attachments Online - Private Embedded File Extractor',
    ogDescription: 'Recover files embedded inside a PDF and download them individually or as a ZIP without uploading the document.',
    twitterTitle: 'Extract PDF Attachments Online',
    twitterDescription: 'Download embedded PDF files individually or as a ZIP with private browser processing.',
  },
  'extract-pdf-bookmarks': {
    path: '/extract-pdf-bookmarks',
    title: 'Extract PDF Bookmarks Online - Export Outline to CSV or JSON',
    description: 'Read a PDF bookmark hierarchy, resolve page destinations, and export the document outline as CSV or JSON with private browser processing.',
    ogTitle: 'Extract PDF Bookmarks Online - Private Outline Exporter',
    ogDescription: 'Inspect nested PDF bookmarks and download their hierarchy and destinations without uploading the document.',
    twitterTitle: 'Extract PDF Bookmarks Online',
    twitterDescription: 'Export PDF bookmark trees and resolved page destinations as CSV or JSON locally in your browser.',
  },
  'extract-pdf-images': {
    path: '/extract-pdf-images',
    title: 'Extract Images from PDF Online - Download Embedded Pictures',
    description: 'Extract unique bitmap images from PDF pages as lossless PNG files. Preserve transparency and download images individually or as a ZIP.',
    ogTitle: 'Extract Images from PDF Online - Private Bitmap Extractor',
    ogDescription: 'Recover embedded bitmap images without rendering complete PDF pages. Free local browser processing.',
    twitterTitle: 'Extract Images from PDF Online',
    twitterDescription: 'Download unique embedded PDF images as lossless PNG files without uploading the document.',
  },
  'extract-pdf-links': {
    path: '/extract-pdf-links',
    title: 'Extract PDF Links Online - Export URLs and Page Destinations',
    description: 'Find web, email, internal-page, external-PDF and other clickable PDF links, then export a safe CSV or JSON audit with local browser processing.',
    ogTitle: 'Extract PDF Links Online - Private Link Annotation Audit',
    ogDescription: 'Inspect clickable PDF annotations and export their targets without uploading the document or opening any link.',
    twitterTitle: 'Extract PDF Links Online',
    twitterDescription: 'Audit PDF link annotations and download CSV or JSON locally in your browser.',
  },
  'html-to-pdf': {
    path: '/html-to-pdf',
    title: 'HTML to PDF Converter Online Free — HTML File to PDF',
    description: 'Paste HTML markup or upload an HTML file, preview the rendered page and export it as a PDF. The browser-based converter is free and needs no account.',
    ogDescription: 'Paste HTML or upload an HTML file, preview the page and export it as a PDF in your browser.',
    twitterTitle: 'HTML to PDF Converter Online Free',
    twitterDescription: 'Paste HTML or upload an HTML file, preview the page and export it as a PDF.',
    ogImage: '/social/html-to-pdf.png',
    ogImageAlt: 'HTML to PDF Converter Online Free',
  },
  'image-to-pdf': {
    path: '/image-to-pdf',
    title: 'Image to PDF Converter Online Free — JPG, PNG to PDF',
    description: 'Convert JPG, PNG and WebP images to PDF online for free. Combine multiple images and adjust page size, orientation and margins. No signup required.',
    ogDescription: 'Convert JPG, PNG and other images to PDF online for free. Combine multiple images into one PDF.',
    twitterTitle: 'Image to PDF Converter Online Free',
    twitterDescription: 'Convert JPG, PNG and other images to PDF instantly. Free, no signup needed.',
    ogImage: '/social/image-to-pdf.png',
    ogImageAlt: 'Image to PDF Converter Online Free',
  },
  'mind-map': {
    path: '/mind-map',
    title: 'AI Mind Map Generator from PDF — Visualise Any Document',
    description: 'Generate an interactive mind map from extracted PDF text with AI. Review the generated topics, descriptions and relationships against the source document.',
    ogDescription: 'Turn extracted PDF content into an interactive visual mind map with AI after signing in.',
    twitterTitle: 'AI Mind Map Generator from PDF',
    twitterDescription: 'Turn extracted PDF content into an interactive visual mind map with AI.',
    ogImage: '/social/mind-map.png',
    ogImageAlt: 'AI Mind Map Generator from PDF',
  },
  'odt-to-pdf': {
    path: '/odt-to-pdf',
    title: 'ODT to PDF Converter Online Free — OpenDocument to PDF',
    description: 'Convert ODT documents to PDF online for free. The browser-based converter rebuilds text, headings, lists and tables with no account required.',
    ogDescription: 'Convert ODT text, headings, lists and tables into a PDF in your browser. Free, no signup.',
    twitterTitle: 'ODT to PDF Converter Online Free',
    twitterDescription: 'Convert ODT text, headings, lists and tables into a PDF in your browser.',
    ogImage: '/social/odt-to-pdf.png',
    ogImageAlt: 'ODT to PDF Converter Online Free',
  },
  'pdf-annotate': {
    path: '/pdf-annotate',
    title: 'Annotate PDF Online — Highlight, Comment & Draw',
    description: 'Annotate PDFs online for free. Highlight text, add comments, draw shapes, insert sticky notes and add freehand markup directly in your browser.',
    ogTitle: 'Annotate PDF Online Free — Highlight, Comment & Mark Up PDFs',
    ogDescription: 'Highlight, comment and draw on supported PDF pages online. Free local browser processing with no signup.',
    twitterTitle: 'Annotate PDF Online Free',
    twitterDescription: 'Highlight, comment and mark up supported PDF pages locally. Free, no signup needed.',
    ogImage: '/social/pdf-annotate.png',
    ogImageAlt: 'Annotate PDF Online Free',
  },
  'pdf-bookmarks-manager': {
    path: '/pdf-bookmarks-manager',
    title: 'PDF Bookmarks Manager Online - Add, Edit and Remove Bookmarks',
    description: 'Add, rename, nest, reorder, retarget, open, close, or delete PDF bookmarks and download a new PDF with private browser processing.',
    ogTitle: 'PDF Bookmarks Manager Online - Private Outline Editor',
    ogDescription: 'Edit a PDF outline tree and download a new navigable PDF without uploading the document.',
    twitterTitle: 'PDF Bookmarks Manager Online',
    twitterDescription: 'Add, rename, nest, reorder, retarget, and delete PDF bookmarks locally in your browser.',
  },
  'pdf-compare': {
    path: '/pdf-compare',
    title: 'Compare PDF Files Online - Find Visual and Text Changes',
    description: 'Compare two PDFs page by page to find visible, textual, page-size, and page-count changes. Free private browser processing with clear difference maps.',
    ogTitle: 'Compare PDF Files Online - Find Every Page Change',
    ogDescription: 'Review visual and textual differences between two PDFs without uploading either document.',
    twitterTitle: 'Compare PDF Files Online',
    twitterDescription: 'Find visual and text changes page by page with private browser processing.',
  },
  'pdf-compressor': {
    path: '/pdf-compressor',
    title: 'Compress PDF Online Free — Reduce PDF File Size',
    description: 'Compress PDF files online with adjustable image quality. Reduce large documents for email, upload or sharing directly in your browser, with no signup.',
    ogDescription: 'Reduce PDF file size with adjustable compression levels. Free, browser-based and no signup required.',
    twitterTitle: 'Compress PDF Online Free',
    twitterDescription: 'Reduce PDF file size with adjustable compression levels in your browser.',
    ogImage: '/social/pdf-compressor.png',
    ogImageAlt: 'Compress PDF Online Free',
  },
  'pdf-cropper': {
    path: '/pdf-cropper',
    title: 'Crop PDF Pages Online Free — Trim PDF Margins',
    description: 'Crop PDF pages online for free. Trim margins, remove whitespace or select a specific area on one page or the entire document. No installation needed.',
    ogDescription: 'Trim margins and crop selected PDF pages online. Free local browser processing with no signup.',
    twitterTitle: 'Crop PDF Pages Online Free',
    twitterDescription: 'Trim margins and crop selected PDF pages in your browser. Free, no signup needed.',
    ogImage: '/social/pdf-cropper.png',
    ogImageAlt: 'Crop PDF Pages Online Free',
  },
  'pdf-editor': {
    path: '/pdf-editor',
    title: 'Edit a PDF Without Adobe Acrobat — Free Online PDF Editor',
    description: 'Edit a PDF without installing Adobe Acrobat — add text, images, highlights, signatures and stamps in your browser. No signup, nothing uploaded.',
    ogDescription: 'Add text, images, shapes, signatures and stamps to supported PDFs. Reorder or rotate pages in your browser, then download a new copy.',
    twitterTitle: 'Edit a PDF Without Adobe Acrobat',
    twitterDescription: 'Add text, images, shapes, signatures and stamps to supported PDFs. Free, no signup or Adobe install required.',
    ogImage: '/social/pdf-editor.png',
    ogImageAlt: 'Edit a PDF Without Adobe Acrobat — Free Online PDF Editor',
  },
  'pdf-flatten': {
    path: '/pdf-flatten',
    title: 'Flatten PDF Online - Make Forms and Annotations Permanent',
    description: 'Flatten PDF form fields or bake every visible page element into a consistent copy. Free private browser processing with no file upload or account.',
    ogDescription: 'Choose a quality-preserving form flatten or a complete visual flatten. Free and private in your browser.',
    twitterDescription: 'Flatten PDF forms and visible annotations privately in your browser.',
    ogImage: '/opengraph-image',
    ogImageAlt: 'EditPDF AI Flatten PDF',
  },
  'pdf-form-builder': {
    path: '/pdf-form-builder',
    title: 'PDF Form Builder Online Free — Create Fillable PDF Forms',
    description: 'Create fillable PDF forms online for free. Add text fields, checkboxes, dropdowns and signatures without installing specialist design software.',
    ogDescription: 'Create professional fillable PDF forms with text fields, checkboxes, signatures and more. Free online.',
    twitterTitle: 'PDF Form Builder Online Free',
    twitterDescription: 'Create professional fillable PDF forms with drag-and-drop. Free, no signup needed.',
    ogImage: '/social/pdf-form-builder.png',
    ogImageAlt: 'PDF Form Builder Online Free',
  },
  'pdf-ocr': {
    path: '/pdf-ocr',
    title: 'PDF OCR Online Free — Extract Text from Scanned PDF',
    description: 'Use AI OCR to extract editable text from scanned PDF pages. Choose a document language, review each page and download the recognized text online.',
    ogDescription: 'Extract editable text from scanned PDF pages with AI OCR, then review and download the recognized text.',
    twitterTitle: 'PDF OCR Online Free',
    twitterDescription: 'Extract editable text from scanned PDF pages with AI OCR and download the result.',
    ogImage: '/social/pdf-ocr.png',
    ogImageAlt: 'PDF OCR — Extract Text from Scanned PDF',
  },
  'pdf-page-labels': {
    path: '/pdf-page-labels',
    title: 'PDF Page Labels Online - Roman Numerals, Prefixes and Sections',
    description: 'Add or edit PDF page labels with decimal numbers, Roman numerals, letters, prefixes, and section restarts using private browser processing.',
    ogTitle: 'PDF Page Labels Online - Private Label Range Editor',
    ogDescription: 'Create viewer navigation labels for PDF front matter, chapters, appendices, and numbered sections without changing page artwork.',
    twitterTitle: 'PDF Page Labels Online',
    twitterDescription: 'Set PDF page labels, prefixes, styles, and numbering restarts locally in your browser.',
  },
  'pdf-page-manager': {
    path: '/pdf-page-manager',
    title: 'PDF Page Manager — Reorder, Delete & Add Pages',
    description: 'Manage PDF pages online for free. Drag to reorder, delete unwanted pages, add blank pages and rotate individual pages. No software install required.',
    ogTitle: 'PDF Page Manager — Reorder, Delete & Add PDF Pages Online',
    ogDescription: 'Drag to reorder, delete or add pages to supported PDFs. Free local browser processing.',
    twitterTitle: 'PDF Page Manager Online',
    twitterDescription: 'Reorder, delete or add PDF pages in your browser. Free, no signup needed.',
    ogImage: '/social/pdf-page-manager.png',
    ogImageAlt: 'PDF Page Manager Online',
  },
  'pdf-password-lock': {
    path: '/pdf-password-lock',
    title: 'PDF Password Lock — Password Protect PDF Free Online',
    description: 'Add password protection to a supported PDF with AES-256 encryption through local WebAssembly processing. Free to use with no account required.',
    ogDescription: 'Add AES-256 password protection to a supported PDF with local browser processing. Free, no account required.',
    twitterDescription: 'Add AES-256 password protection to a supported PDF locally. Free, no account required.',
    ogImage: '/social/pdf-password-lock.png',
    ogImageAlt: 'PDF Password Lock',
  },
  'pdf-redactor': {
    path: '/pdf-redactor',
    title: 'Cover Sensitive PDF Content Online — Add Opaque Marks',
    description: 'Place opaque black marks over selected areas of a PDF and download the marked copy. Processing runs locally in your browser with no account required.',
    ogDescription: 'Place opaque marks over selected PDF areas and download a new copy with local browser processing.',
    twitterTitle: 'Cover Sensitive PDF Content Online',
    twitterDescription: 'Place opaque marks over selected PDF areas locally in your browser.',
    ogImage: '/social/pdf-redactor.png',
    ogImageAlt: 'Redact PDF Online Free',
  },
  'pdf-repair': {
    path: '/pdf-repair',
    title: 'Repair PDF Online - Recover a Damaged PDF',
    description: 'Repair recoverable PDF structure errors privately in your browser. Free local processing with no file upload, no account, and no change to the original file.',
    ogDescription: 'Rebuild recoverable PDF structure errors locally in your browser. Free to use with no account.',
    twitterDescription: 'Repair recoverable PDF structure errors privately in your browser.',
    ogImage: '/opengraph-image',
    ogImageAlt: 'EditPDF AI Repair PDF',
  },
  'pdf-signer': {
    path: '/pdf-signer',
    title: 'PDF E-Signer Online Free — Add a Signature to PDF',
    description: 'Draw, type or upload a signature image, place it on a supported PDF page and download the new copy. This browser-based tool requires no account.',
    ogDescription: 'Draw, type or upload a signature image and place it on a supported PDF page. No account needed.',
    twitterTitle: 'Sign PDF Online Free',
    twitterDescription: 'Draw, type or upload a signature image and place it on a supported PDF page. No account needed.',
    ogImage: '/social/pdf-signer.png',
    ogImageAlt: 'Sign PDF Online Free',
  },
  'pdf-summarizer': {
    path: '/pdf-summarizer',
    title: 'AI PDF Summarizer Online — Summarize PDF Documents',
    description: `Summarize extracted PDF text with AI and choose a brief, standard or detailed result. Signed-in Free includes ${FREE_AI_DAILY_LIMIT} AI actions per UTC day.`,
    ogDescription: 'Create a brief, standard or detailed AI summary of a PDF document online.',
    twitterTitle: 'AI PDF Summarizer Online',
    twitterDescription: 'Create a brief, standard or detailed AI summary of a PDF document online.',
    ogImage: '/social/pdf-summarizer.png',
    ogImageAlt: 'AI PDF Summarizer Online Free',
  },
  'pdf-to-excel': {
    path: '/pdf-to-excel',
    title: 'PDF to Excel Converter Online — Export Tables to XLS',
    description: 'Use AI to extract tables from PDF pages into an editable Excel-compatible XLS spreadsheet. Sign in to convert and review the generated workbook.',
    ogDescription: 'Extract PDF table data into an editable Excel-compatible XLS spreadsheet with AI.',
    twitterTitle: 'PDF to Excel Converter Online',
    twitterDescription: 'Extract PDF table data into an editable Excel-compatible XLS spreadsheet with AI.',
    ogImage: '/social/pdf-to-excel.png',
    ogImageAlt: 'PDF to Excel Converter Online',
  },
  'pdf-to-images': {
    path: '/pdf-to-images',
    title: 'PDF to Image Converter Online Free — PDF to JPG, PNG',
    description: 'Convert PDF pages to high-quality JPG or PNG images online for free. Extract every page as an image or choose specific pages. No signup, works in browser.',
    ogDescription: 'Convert PDF pages to high-quality JPG or PNG images. Free, instant, no signup needed.',
    twitterTitle: 'PDF to Image Converter Online Free',
    twitterDescription: 'Convert PDF pages to JPG or PNG images instantly. Free, no signup.',
    ogImage: '/social/pdf-to-images.png',
    ogImageAlt: 'PDF to Image Converter Online Free',
  },
  'pdf-to-ppt': {
    path: '/pdf-to-ppt',
    title: 'PDF to PowerPoint Online — Create an Editable PPTX',
    description: 'Use AI to turn extracted PDF text into a new editable PowerPoint presentation with structured slides. Sign in to create and download the PPTX.',
    ogDescription: 'Turn extracted PDF text into a newly structured, editable PowerPoint presentation with AI.',
    twitterTitle: 'PDF to PowerPoint Online',
    twitterDescription: 'Turn extracted PDF text into a newly structured, editable PowerPoint presentation with AI.',
    ogImage: '/social/pdf-to-ppt.png',
    ogImageAlt: 'PDF to PowerPoint Converter Online',
  },
  'pdf-to-word': {
    path: '/pdf-to-word',
    title: 'PDF to Word Converter Online — Editable DOC File',
    description: 'Use AI to convert PDF text and tables into an editable Word-compatible DOC file. Sign in to convert online; complex source formatting may vary.',
    ogDescription: 'Convert PDF text and tables into an editable Word-compatible DOC file with AI.',
    twitterTitle: 'PDF to Word Converter Online',
    twitterDescription: 'Convert PDF text and tables into an editable Word-compatible DOC file with AI.',
    ogImage: '/social/pdf-to-word.png',
    ogImageAlt: 'PDF to Word Converter Online',
  },
  'pdf-translator': {
    path: '/pdf-translator',
    title: 'AI PDF Translator — Translate PDFs Online',
    description: 'Translate PDF documents into 77 languages with AI. Translate contracts, reports and forms in seconds, then download the result online.',
    ogTitle: 'AI PDF Translator Online — Translate into 77 Languages',
    ogDescription: 'Translate extracted PDF text into one of 77 listed languages with AI, review the result and download a rebuilt PDF.',
    twitterTitle: 'AI PDF Translator Online',
    twitterDescription: 'Translate extracted PDF text into one of 77 listed languages with AI and download the rebuilt result.',
    ogImage: '/social/pdf-translator.png',
    ogImageAlt: 'AI PDF Translator Online Free',
  },
  'pdf-unlock': {
    path: '/pdf-unlock',
    title: 'Unlock PDF Online - Remove a Known PDF Password',
    description: 'Remove password protection from a PDF you own. Free, private browser processing with no file upload, no account, and no loss of quality.',
    ogDescription: 'Remove a known password from a supported PDF with local browser processing. Free, no account required.',
    twitterDescription: 'Remove a known PDF password privately in your browser.',
    ogImage: '/opengraph-image',
    ogImageAlt: 'EditPDF AI Unlock PDF',
  },
  'pdf-viewer': {
    path: '/pdf-viewer',
    title: 'PDF Viewer Online Free — Open & Read PDF in Browser',
    description: 'View supported PDF files online for free. Open, zoom, search and navigate pages in your browser without installing desktop PDF software.',
    ogDescription: 'Open and read supported PDF files in your browser. Zoom, search and navigate pages with no install.',
    twitterTitle: 'PDF Viewer Online Free',
    twitterDescription: 'Open, zoom and read supported PDF files in your browser. Free, no install needed.',
    ogImage: '/social/pdf-viewer.png',
    ogImageAlt: 'PDF Viewer Online Free',
  },
  'ppt-to-pdf': {
    path: '/ppt-to-pdf',
    title: 'PowerPoint to PDF Converter Online Free — PPTX to PDF',
    description: 'Convert PPTX slide text and tables into rebuilt PDF pages online. Preview the generated presentation and download it for free with no account required.',
    ogDescription: 'Convert PPTX slide text and tables into rebuilt PDF pages online. Free, no signup required.',
    twitterTitle: 'PowerPoint to PDF Converter Online Free',
    twitterDescription: 'Convert supported PPTX slide text into newly styled PDF pages locally in your browser. Free, no signup needed.',
    ogImage: '/social/ppt-to-pdf.png',
    ogImageAlt: 'PowerPoint to PDF Converter Online Free',
  },
  'pricing': {
    path: '/pricing',
    title: 'Pricing & Plans | EditPDF AI',
    description: 'Compare EditPDF AI Free and Pro access, including daily AI usage, browser-based PDF tools, subscription billing and account management options.',
    ogDescription: 'Compare EditPDF AI Free and Pro access, AI usage allowances and subscription options.',
    twitterDescription: 'Compare EditPDF AI Free and Pro access, AI usage allowances and subscription options.',
    ogImage: '/opengraph-image',
    ogImageAlt: 'EditPDF AI Pricing',
  },
  'privacy': {
    path: '/privacy',
    title: 'Privacy Policy | EditPDF AI',
    description: 'Read the EditPDF AI privacy policy to learn what account, payment, analytics and document-processing data is handled when you use the website.',
    ogDescription: 'Read how EditPDF AI handles browser-local files, AI request content, account records, analytics, subscriptions and document-processing data.',
    ogImage: '/opengraph-image',
    ogImageAlt: 'EditPDF AI Privacy Policy',
  },
  'quiz-creator': {
    path: '/quiz-creator',
    title: 'AI Quiz Creator from PDF — Generate Practice Questions',
    description: 'Create multiple-choice, short-answer or mixed practice questions from a PDF with AI. Sign in, choose the question count and review answers online.',
    ogDescription: 'Generate multiple-choice, short-answer or mixed practice questions from a PDF with AI.',
    twitterTitle: 'AI Quiz Creator from PDF',
    twitterDescription: 'Generate multiple-choice, short-answer or mixed practice questions from a PDF with AI.',
    ogImage: '/social/quiz-creator.png',
    ogImageAlt: 'AI Quiz Creator from PDF',
  },
  'remove-pdf-links': {
    path: '/remove-pdf-links',
    title: 'Remove Links from PDF Online - Disable All Clickable Links',
    description: 'Remove web, email, page, file, form and JavaScript link annotations from a PDF locally while keeping the visible page content unchanged.',
    ogTitle: 'Remove PDF Links Online - Private Browser Tool',
    ogDescription: 'Create a link-free PDF copy without uploading the document or changing visible link text.',
    twitterTitle: 'Remove PDF Links Online',
    twitterDescription: 'Disable clickable PDF link annotations privately in your browser.',
  },
  'remove-pdf-metadata': {
    path: '/remove-pdf-metadata',
    title: 'Remove PDF Metadata Online - Clean Hidden Document Properties',
    description: 'Remove PDF properties, XMP packets, document IDs, page metadata and optional annotation identity data with private processing in your browser.',
    ogTitle: 'Remove PDF Metadata Online - Private Document Cleaner',
    ogDescription: 'Clean hidden PDF properties and identifiers locally without changing page quality.',
    twitterTitle: 'Remove PDF Metadata Online',
    twitterDescription: 'Strip hidden document properties, XMP metadata, and identifiers with private browser processing.',
  },
  'rotate-pdf': {
    path: '/rotate-pdf',
    title: 'Rotate PDF Online Free — Rotate Pages in Seconds',
    description: 'Rotate PDF pages online for free. Rotate a single page, all pages, or a custom range — 90°, 180° or 270°. Works in your browser, no install needed.',
    ogDescription: 'Rotate supported PDF pages by 90°, 180° or 270° with local browser processing and no signup.',
    twitterTitle: 'Rotate PDF Online Free',
    twitterDescription: 'Rotate supported PDF pages by 90°, 180° or 270° in your browser.',
    ogImage: '/social/rotate-pdf.png',
    ogImageAlt: 'Rotate PDF Online Free',
  },
  'rtf-to-pdf': {
    path: '/rtf-to-pdf',
    title: 'RTF to PDF Converter Online Free — Rich Text to PDF',
    description: 'Extract readable text from an RTF file and export it as a clean PDF online. Choose page settings and download the result without creating an account.',
    ogDescription: 'Extract readable RTF text and export it as a clean PDF online. Free, no signup required.',
    twitterTitle: 'RTF to PDF Converter Online Free',
    twitterDescription: 'Extract readable RTF text and export it as a clean PDF online.',
    ogImage: '/social/rtf-to-pdf.png',
    ogImageAlt: 'RTF to PDF Converter Online Free',
  },
  'scan-to-pdf': {
    path: '/scan-to-pdf',
    title: 'Scan to PDF Online Free — Camera Document Scanner',
    description: 'Turn your camera into a document scanner. Auto-detect edges, fix perspective, and export a clean multi-page PDF. Free, no signup, runs in your browser.',
    ogDescription: 'Capture paper documents with your camera, auto-crop and straighten them, and save a multi-page PDF. Free and private — nothing leaves your browser.',
    twitterDescription: 'Capture paper documents with your camera and export a clean multi-page PDF. Free, no signup needed.',
    ogImage: '/opengraph-image',
    ogImageAlt: 'Scan to PDF — Camera Document Scanner',
  },
  'support': {
    path: '/support',
    title: 'Help & Support | EditPDF AI',
    description: 'Find answers to common questions about EditPDF AI tools, billing, and account management. Contact support if you need further help.',
    ogDescription: 'Find answers to common questions about EditPDF AI tools, billing, and account management.',
    ogImage: '/opengraph-image',
    ogImageAlt: 'EditPDF AI Support',
  },
  'terms': {
    path: '/terms',
    title: 'Terms of Service | EditPDF AI',
    description: 'Read the EditPDF AI terms of service, including account, subscription, acceptable-use and service conditions for browser-based PDF and AI tools.',
    ogDescription: 'Read the EditPDF AI terms of service and conditions of use for our PDF and AI tools.',
    ogImage: '/opengraph-image',
    ogImageAlt: 'EditPDF AI Terms of Service',
  },
  'txt-to-pdf': {
    path: '/txt-to-pdf',
    title: 'TXT to PDF Converter Online Free — Text File to PDF',
    description: 'Convert plain text TXT files to PDF online for free. Choose font, size and margins. Download a clean, formatted PDF in seconds. No signup required.',
    ogDescription: 'Convert plain text TXT files to clean PDFs. Choose font and formatting. Free, no signup.',
    twitterTitle: 'TXT to PDF Converter Online Free',
    twitterDescription: 'Convert plain text files to PDF instantly. Free, no signup needed.',
    ogImage: '/social/txt-to-pdf.png',
    ogImageAlt: 'TXT to PDF Converter Online Free',
  },
  'word-to-pdf': {
    path: '/word-to-pdf',
    title: 'Word to PDF Converter Online Free — DOCX to PDF',
    description: 'Convert DOCX documents to PDF online for free. The browser-based converter rebuilds text, headings, lists and tables with no account required.',
    ogDescription: 'Convert DOCX text, headings, lists and tables into a PDF in your browser. Free, no signup.',
    twitterTitle: 'Word to PDF Converter Online Free',
    twitterDescription: 'Convert DOCX text, headings, lists and tables into a PDF in your browser.',
    ogImage: '/social/word-to-pdf.png',
    ogImageAlt: 'Word to PDF Converter Online Free',
  },
  'sign-in': {
    path: '/sign-in',
    canonicalPath: null,
    title: 'Sign In to EditPDF AI',
    description: 'Sign in to your EditPDF AI account to use account-based AI tools, review your plan and manage your subscription settings.',
    robots: { index: false, follow: true },
  },
  'sign-up': {
    path: '/sign-up',
    canonicalPath: null,
    title: 'Create an EditPDF AI Account',
    description: 'Create an EditPDF AI account to access account-based AI tools and the daily AI allowance available on the free plan.',
    robots: { index: false, follow: true },
  },
  'dashboard': {
    path: '/dashboard',
    canonicalPath: null,
    title: 'Dashboard — EditPDF AI',
    description: 'View your EditPDF AI account, plan details, AI usage and subscription controls from the private account dashboard.',
    robots: { index: false, follow: true },
  },
  'manage-subscription': {
    path: '/manage-subscription',
    canonicalPath: null,
    title: 'Manage Subscription — EditPDF AI',
    description: 'Review and manage the subscription associated with your EditPDF AI account. This private account page is not indexed.',
    robots: { index: false, follow: true },
  },
  'checkout': {
    path: '/checkout',
    canonicalPath: null,
    title: 'Subscription Checkout — EditPDF AI',
    description: 'Complete an EditPDF AI subscription purchase through the private checkout flow. Payment fields and subscription processing are provided by Stripe.',
    robots: { index: false, follow: true },
  },
  'checkout-confirm': {
    path: '/checkout/confirm',
    canonicalPath: null,
    title: 'Confirming Payment — EditPDF AI',
    description: 'Confirm an EditPDF AI subscription payment and return to the application after the private checkout process completes.',
    robots: { index: false, follow: true },
  },
  'cancel': {
    path: '/cancel',
    canonicalPath: null,
    title: 'Subscription Status — EditPDF AI',
    description: 'Review the result of an EditPDF AI subscription cancellation or return to account management from this private application page.',
    robots: { index: false, follow: true },
  },
} satisfies Record<string, PageSeoConfig>

export type PageSeoKey = keyof typeof PAGE_SEO

const CONFIGURED_PAGES: PageSeoConfig[] = Object.values(PAGE_SEO)

export const INDEXABLE_PAGE_SEO = CONFIGURED_PAGES.filter(
  page => page.robots?.index !== false && page.canonicalPath !== null,
)

export const NOINDEX_PAGE_SEO = CONFIGURED_PAGES.filter(
  page => page.robots?.index === false,
)

export function metadataFor(key: PageSeoKey) {
  return buildPageMetadata(PAGE_SEO[key])
}

// Compatibility export for existing tool layouts; it references PAGE_SEO and
// does not create a second metadata source.
export const TOOL_METADATA = PAGE_SEO
