import { buildToolMetadata } from '@/lib/seo/metadata'
import { TOOL_METADATA } from '@/lib/seo/routes'

export const metadata = buildToolMetadata(TOOL_METADATA['remove-pdf-metadata'])

// SoftwareApplication + BreadcrumbList schema for this page is generated by
// <ToolSEOSection> (rendered from page.tsx, driven by src/lib/toolSeoData.ts)
// — do not re-declare either here, it would duplicate that output.
export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
