import { buildToolMetadata } from '@/lib/seo/metadata'
import { TOOL_METADATA } from '@/lib/seo/routes'

export const metadata = buildToolMetadata(TOOL_METADATA['pdf-unlock'])

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebApplication',
  '@id': 'https://www.editpdfai.com/pdf-unlock#webapp',
  provider: { '@id': 'https://www.editpdfai.com/#organization' },
  name: 'Unlock PDF',
  url: 'https://www.editpdfai.com/pdf-unlock',
  applicationCategory: 'UtilitiesApplication',
  operatingSystem: 'Web',
  offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
  description: 'Remove password protection from an authorized PDF locally in the browser.',
  featureList: 'Known-password PDF decryption, local WebAssembly processing, no file upload, quality-preserving output',
  browserRequirements: 'Requires JavaScript and WebAssembly. Works in current versions of Chrome, Firefox, Safari, and Edge.',
}

// BreadcrumbList for this page is generated by <ToolSEOSection> (rendered
// from page.tsx) — not re-declared here, it would duplicate that output.
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      {children}
    </>
  )
}

