import { buildToolMetadata } from '@/lib/seo/metadata'
import { TOOL_METADATA } from '@/lib/seo/routes'
import { ORGANIZATION_ID } from '@/lib/seo/site'

export const metadata = buildToolMetadata(TOOL_METADATA['pdf-password-lock'])

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebApplication',
  '@id': 'https://www.editpdfai.com/pdf-password-lock#webapp',
  provider: { '@id': ORGANIZATION_ID },
  name: 'PDF Password Lock',
  url: 'https://www.editpdfai.com/pdf-password-lock',
  applicationCategory: 'UtilitiesApplication',
  operatingSystem: 'Web',
  offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
  description: 'Add a password to any PDF instantly with AES-256 encryption. Free, runs in your browser, no account required.',
  featureList: 'AES-256 PDF encryption, open password, permissions password, browser-based processing',
  browserRequirements: 'Requires JavaScript. Works in Chrome, Firefox, Safari, Edge.',
}

// BreadcrumbList for this page is generated by <ToolSEOSection> (rendered
// from page.tsx) — not re-declared here, it would duplicate that output.
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      {children}
    </>
  )
}
