import { buildToolMetadata } from '@/lib/seo/metadata'
import { TOOL_METADATA } from '@/lib/seo/routes'

export const metadata = buildToolMetadata(TOOL_METADATA['pdf-flatten'])

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebApplication',
  '@id': 'https://www.editpdfai.com/pdf-flatten#webapp',
  provider: { '@id': 'https://www.editpdfai.com/#organization' },
  name: 'Flatten PDF',
  url: 'https://www.editpdfai.com/pdf-flatten',
  applicationCategory: 'UtilitiesApplication',
  operatingSystem: 'Web',
  offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
  description: 'Make PDF form fields or every visible page element permanent using private browser processing.',
  featureList: 'Quality-preserving form flattening, full visual flattening, signature detection, local browser processing, no file upload',
  browserRequirements: 'Requires JavaScript. Works in current versions of Chrome, Firefox, Safari, and Edge.',
}

// BreadcrumbList for this page is generated by <ToolSEOSection> (rendered
// from page.tsx) — not re-declared here, it would duplicate that output.
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      {children}
    </>
  )
}
