import { buildToolMetadata } from '@/lib/seo/metadata'
import { TOOL_METADATA } from '@/lib/seo/routes'
import { ORGANIZATION_ID } from '@/lib/seo/site'

export const metadata = buildToolMetadata(TOOL_METADATA['pdf-watermark'])

const jsonLdApp = {
  '@context': 'https://schema.org',
  '@type': 'WebApplication',
  '@id': 'https://www.editpdfai.com/pdf-watermark#webapp',
  provider: { '@id': ORGANIZATION_ID },
  name: 'PDF Watermarker',
  url: 'https://www.editpdfai.com/pdf-watermark',
  applicationCategory: 'UtilitiesApplication',
  operatingSystem: 'Web',
  offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
  description: 'Add custom text or image watermarks to any PDF online. Control opacity, angle, position, color and font size. Free, no signup.',
  featureList: 'Text Watermarks, Image Watermarks, Opacity Control, Angle Control, Position Control, Color Selection, Font Size, Batch All Pages',
  browserRequirements: 'Requires JavaScript. Works in Chrome, Firefox, Safari, Edge.',
}

// FAQPage schema for this page is generated by <ToolSEOSection> (rendered
// from page.tsx, driven by src/lib/toolSeoData.ts) — not re-declared here,
// it would duplicate that output (and could drift from the visible FAQ copy).
export default function PDFWatermarkLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdApp) }} />
      {children}
    </>
  )
}
